### ISSUE TITLE
Outsource to HEALPix.jl ?

### ISSUE THREAD

**Issue by milankl** [jmert/CMB.jl#73]
Hey Justin, was just wondering whether it makes sense to move your existing code to define the HEALPix grid and functions for it to a separate package, say HEALPix.jl. I see that you are defining a lot of functions for the grid, but I was wondering whether it also makes sense to create a `struct HEALPixGrid{T,H,K}` that efficiently stores data on that grid, something like
```julia
abstract type AbstractHEALPixGrid end    # not sure whether it makes sense to subtype it from any other existing array

struct HEALPixGrid{T,H,K} <: AbstractHEALPixGrid
    data::Vector{T}
    ...
end

# make H=4, K=3 the default
HEALPixGrid{T}(data::AbstractVector,...) = HEALPixGrid{eltype{data},4,3}(data,...)
```
then we can more easily dispatch functions and clearly define projections onto that grid and back. What do you think?

**Comment by jmert** [comment]
I've sorta already done that once before in the context of representing a large matrix operator which operates on a HEALPix map and produces an RA/Dec map — see https://github.com/jmert/CMB.jl/blob/6f772d80889752713a1e924c57279d82f1c0e82b/src/pixelizations.jl#L44-L59

It explicitly doesn't store data inline because its role is to describe the subset of pixels which are relevant for interpreting the columns of the matrix operator.

**Comment by jmert** [comment]
CMB is a bad name to register in the General registry, and the purpose of this package is I think too specific to ever really consider registering it as a whole — the purpose has always been to recreate a specific calculation in Julia which was a big component of my thesis work (which was in a collaboration doing experimental cosmology).

(And I guess for a bit more context on why I didn't use Healpix.jl, it's because my work on a version of this package started back in 2014 — although current git history doesn't go back that far since I've branched/recreated/restarted this project a couple of times — when Healpix.jl was either non-existent or didn't meet my needs.)

**Comment by milankl** [comment]
Would you in general be interested to put healpix.jl from this repository into jmert/HEALPix.jl and register it as v0.1? All the functionality in there and documentation is great, and we'd like to use it. But for the dependency it should be registered as an official package. It doesn't need to be v1 or in some form stable, if you feel like releasing a breaking change then I'm sure you'd very good reasons to do so.

**Comment by milankl** [comment]
I understand the conflict with CMB.jl and it being more your work in progress repository, but I think the spin-offs (HEALPix.jl or SphericalHarmonicTransforms.jl) are general enough to make them interesting to a wider audience outside of astronomy/cosmology, like weather and climate people.

**Comment by jmert** [comment]
I'm certainly open to splitting the code into jmert/Healpix.jl and registering it in my registry — the barrier to doing that is very low. The obvious conflict with registering in General is that it'd need a new name.

**Comment by milankl** [comment]
I think HEALPix.jl is great to be honest, it even has a wiki entry https://en.wikipedia.org/wiki/HEALPix

**Comment by jmert** [comment]
What I mean is that https://github.com/JuliaRegistries/General/tree/master/H/Healpix already exists and points to ziotom78/Healpix.jl. I'd need to rename to something else to get it registered in General.

**Comment by milankl** [comment]
I didn't know of ziotom78's implementation 🙈 what was your reason to write your own?

**Comment by jmert** [comment]
@milankl I've finally had an afternoon to return to this issue. I've extracted the Healpix module from this package and made it available via a new package (https://github.com/jmert/Healpix.jl), which again is **not** part of the Julia General registry, instead requiring use of my [personal registry](https://github.com/jmert/Registry.jl) or adding by git path explicitly.

**Comment by milankl** [comment]
Thanks Justin, this is great. In the meantime we used Healpix.jl, but then realised that the functions of that package we actually need are so few that we just implemented them ourselves to avoid a big dependency. Maybe you find that interesting, SpeedyWeather.jl now runs with the standard HEALPix grid and a variant we call the HEALPix4 grid, which only has 4 base pixels instead of 12. The reason is that we usually want 4x as many longitudes at the Equator as there are latitudes - which you don't get with HEALPix, but with HEALPix4. However, I'm not sure what happens if we don't follow that rule in our application. Quick overview

![image](https://user-images.githubusercontent.com/25530332/198120797-8e2aa36d-04ac-42d6-b007-f0ab142c4af9.png)

Btw, just to be open about this: Given that your grid-flexible transform implementation has massively influenced ours, when we start writing a paper about HEALPix grids for spectral weather models then I'd like to invite you as a co-author.

**Comment by jmert** [comment]
> Thanks Justin, this is great. In the meantime we used Healpix.jl, but then realised that the functions of that package we actually need are so few that we just implemented them ourselves to avoid a big dependency. Maybe you find that interesting, SpeedyWeather.jl now runs with the standard HEALPix grid and a variant we call the HEALPix4 grid, which only has 4 base pixels instead of 12. The reason is that we usually want 4x as many longitudes at the Equator as there are latitudes - which you don't get with HEALPix, but with HEALPix4. However, I'm not sure what happens if we don't follow that rule in our application. Quick overview
>
> ![image](https://user-images.githubusercontent.com/25530332/198120797-8e2aa36d-04ac-42d6-b007-f0ab142c4af9.png)

In case you haven't come across this reference before, https://arxiv.org/abs/astro-ph/0412607 describes how HEALPix in its base-12 pixel format is just one realization of a class of similar pixelizations — your choice to reduce the number of base latitudes can be described within their scheme (IIRC).


> Btw, just to be open about this: Given that your grid-flexible transform implementation has massively influenced ours, when we start writing a paper about HEALPix grids for spectral weather models then I'd like to invite you as a co-author.

I'd be honored! I look forward to reading and learning!
